[package]
name = "quasar-api"
version = "2.1.0"
description = "QuaSAR hardware API and adapters (cross-platform)"
authors = [
    "kernel386 <kernel386@mail.ru>",
    "whs31 <ryazantsev.dl@edu.spbstu.ru>"
]

[dependencies]
cmake = { version = "0.1.3", distribution = "sources" }
leaf = { version = "0.4.4", distribution = "static" }